### ISSUE TITLE
Consider adding a donation link

### ISSUE THREAD

**Issue by JKolios** [balourdos/MemonomenaPeristatika.gr#13]
I would personally be glad to contribute towards hosting costs for the videos, proxies, or whatever else added features might come up. I believe there would be others willing to follow as well.

**Comment by balourdos** [comment]
Thank you for suggesting this! Currently we have no costs at all; but as we just started self-hosting all videos, this might change, so we'll keep this mind.

**Comment by balourdos** [comment]
Thank you again for the suggestion and your willingness to contribute! We just wanted to mention that we added donation addresses on the site, as the hosting costs started increasing due to high traffic.
