### ISSUE TITLE
Event corrections

### ISSUE THREAD

**Issue by dimkarakostas** [balourdos/MemonomenaPeristatika.gr#23]
- 26 Ιανουαρίου 2021, Μενίδι: Αστυνομικής χτυπάει 11χρονο παιδί -> 26 Ιανουαρίου _2020_
- 15 Ιουλίου 2020, Αθήνα: Ξυλοδαρμός Τιτκώβ και Λάλου -> _17_ Ιουλίου 2020
- 15 Ιουνίου 2020, Αθήνα: Τοποθέτηση μπουκαλιού σε σακίδιο συλληφθέντα  -> _17 Ιουλίου_ 2020
- 27 Φεβρουαρίου 2020, Λέσβος: Σπάσιμο αυτοκινήτων + 26 Φεβρουαρίου 2020, Χίος: Καταστροφή αυτοκινήτων -> _διπλοκαταχώρηση_
- 26 Φεβρουαρίου 2020, Αθήνα: Κουκουλοφόρος αστυνομικός εκτός υπηρεσίας βγάζει όπλο εναντίον φοιτητών στο προαύλιο της ΑΣΟΕΕ -> _24_ Φεβρουαρίου 2020
- 17 Νοεμβρίου 2019, Εξάρχεια: Αστυνομικοί χτυπούν κορίτσι + Eξάρχεια: Ξυλοδαρμός πολιτών -> _διπλοκαταχώρηση_

**Comment by balourdos** [comment]
Ευχαριστούμε για τις διορθώσεις, έχουν ανέβει στο site!
